name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    uses: Solipath/DotNet-CSharp-Solipath-Example/.github/workflows/_build.yml@main
